<a href="https://colab.research.google.com/github/pipaber/Python-Programming101/blob/main/01_Introduccion_a_Python/06_NumPy_Arrays_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


# **NumPy Arrays**


**Objetivo**

El objetivo de este laboratorio es brindar una comprensión profunda y práctica de la biblioteca NumPy en Python, una herramienta esencial para el cálculo numérico y el análisis en data science.


**Índice del Laboratorio**

- 1. Introducción y Configuración
- 2. Creación de Arrays
- 3. Propiedades de los Arrays
- 4. Operaciones Básicas
- 5. Indexación y Slicing
- 6. Manipulación de la Forma
- 7. Broadcasting
- 8. Álgebra Lineal


## 1. Introducción y Configuración

**¿Qué es NumPy?**

NumPy (Numerical Python) es una librería esencial en Python para el cálculo numérico y el análisis de datos. Proporciona:


- **Arrays multidimensionales:** Estructuras de datos eficientes para almacenar y manipular grandes conjuntos de datos numéricos.
- **Funciones matemáticas:** Operaciones vectorizadas para realizar cálculos rápidos y eficientes.
- **Herramientas avanzadas:** Funciones para álgebra lineal, transformadas de Fourier, generación de números aleatorios, y más.


**Instalación y Configuración**

Antes de comenzar, asegúrate de tener NumPy instalado en tu entorno de Python. Puedes instalarlo usando pip:

In [3]:
# Instalación

try:
    import numpy as np
    print("NumPy ya se encuentra instalado.")
except ImportError:
    print("NumPy no se encuentra instalado. Instalando...")

print("Versión de NumPy:", np.__version__)


NumPy ya se encuentra instalado.
Versión de NumPy: 2.0.2


## 2. Creación de Arrays

Los arrays son la base de NumPy y representan colecciones de elementos del mismo tipo de datos. Veamos cómo crearlos de diferentes maneras.

### 2.1. Crear un Array desde una Lista



**Ejemplo 1:** Array Unidimensional

In [ ]:
# Array unidimensional desde una lista
array_1d = np.array([10, 20, 30, 40])
print("Array 1D:", array_1d)


Array 1D: [10 20 30 40]


**Ejemplo 2:** Array Multidimensional


In [ ]:
# Array bidimensional desde una lista de listas
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:\n", array_2d)


Array 2D:
 [[1 2 3]
 [4 5 6]]


**Ejercicios**

Crea un array unidimensional con los números del 5 al 15.


In [ ]:
np.arange(5,16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Genera un array bidimensional de 2 filas y 3 columnas con números decimales.


In [ ]:
np.random.rand(2,3)

array([[0.15453843, 0.44037634, 0.66166563],
       [0.22330527, 0.58808245, 0.58000371]])

Crea un array tridimensional de forma (2, 2, 2) con números enteros.

In [ ]:
np.random.randint(0,100,(2,2,2))

array([[[76, 66],
        [ 6,  4]],

       [[31, 36],
        [29, 88]]])

### 2.2. Arrays Predefinidos

NumPy ofrece funciones para crear arrays con valores predefinidos, lo cual es útil para inicializar matrices o vectores.

**Ejemplo 1:** Arrays de Ceros y Unos

In [ ]:
# Array de ceros de forma (3, 3)
zeros_array = np.zeros((3, 3))
print("Array de ceros:\n", zeros_array)

# Array de unos de forma (2, 4)
ones_array = np.ones((2, 4))
print("Array de unos:\n", ones_array)


**Ejemplo 2:** Array de Valores Constantes


In [ ]:
# Array lleno con el valor 7 de forma (3, 2)
full_array = np.full((3, 2), 7)
print("Array lleno de 7:\n", full_array)


**Ejercicios**

Crea un array de ceros de forma (5, 5).


Genera un array de unos de forma (4, 1).


Crea un array lleno con el número pi (π) de forma (2, 3).

### 2.3. Arrays con Rangos

Puedes crear arrays con secuencias de números utilizando funciones como arange y linspace.

**Ejemplo 1:** Usando arange


In [ ]:
# Números del 0 al 9
arange_array = np.arange(10)
print("Array con arange:", arange_array)

# Números del 5 al 20 con paso de 3
step_array = np.arange(5, 21, 3)
print("Array con paso de 3:", step_array)


**Ejemplo 2:** Usando linspace


In [ ]:
# 5 números igualmente espaciados entre 0 y 1
linspace_array = np.linspace(0, 1, 5)
print("Array con linspace:", linspace_array)

# 4 números igualmente espaciados entre 10 y 50
linspace_array2 = np.linspace(10, 50, 4)
print("Otro array con linspace:", linspace_array2)


**Ejercicios**

Crea un array con números del 0 al 50, cada 5 unidades.


Genera un array con 7 números igualmente espaciados entre 2 y 3.


Crea un array con números enteros del 10 al 1 en orden descendente.

## 2.4. Arrays Aleatorios

NumPy incluye funciones para generar arrays con números aleatorios, lo cual es útil en simulaciones y pruebas.



**Ejemplo 1:** Números Aleatorios Uniformes

In [ ]:
# Array de forma (2, 3) con números aleatorios entre 0 y 1
random_array = np.random.rand(2, 3)
print("Array aleatorio uniforme:\n", random_array)


**Ejemplo 2:** Números Aleatorios Enteros

In [ ]:
# Array de enteros aleatorios entre 1 y 100 de forma (3, 3)
random_int_array = np.random.randint(1, 100, (3, 3))
print("Array aleatorio de enteros:\n", random_int_array)


**Ejercicios**

Genera un array de forma (5,) con números aleatorios entre 0 y 1.


Crea un array de enteros aleatorios entre 50 y 100 de forma (4, 2).


Genera un array aleatorio de forma (3, 3) y multiplica todos sus elementos por 10.

## 3. Propiedades de los Arrays

Es importante comprender las propiedades de los arrays para manipularlos eficazmente.

**Ejemplo 1:** Explorando las Propiedades

In [5]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", array)
print("Dimensiones (ndim):", array.ndim)
print("Forma (shape):", array.shape)
print("Tamaño total (size):", array.size)
print("Tipo de datos (dtype):", array.dtype)


Array:
 [[1 2 3]
 [4 5 6]]
Dimensiones (ndim): 2
Forma (shape): (2, 3)
Tamaño total (size): 6
Tipo de datos (dtype): int64


**Ejemplo 2:** Tamaño en Memoria


In [6]:
print("Tamaño en bytes de un elemento (itemsize):", array.itemsize)
print("Tamaño total en memoria (nbytes):", array.nbytes)


Tamaño en bytes de un elemento (itemsize): 8
Tamaño total en memoria (nbytes): 48


**Ejercicios**

Crea un array de forma (3, 4) y muestra todas sus propiedades.


Cambia el tipo de datos de un array a float64 y verifica el cambio en dtype.


Calcula el tamaño total en memoria de un array de forma (1000,) con tipo de datos int32.

## 4. Operaciones Básicas

Las operaciones vectorizadas en NumPy permiten realizar cálculos de forma eficiente sin necesidad de bucles.

### 4.1. Operaciones Matemáticas

**Ejemplo 1:** Operaciones Elemento a Elemento

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)
print("División:", a / b)


Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


**Ejemplo 2:** Operaciones con Escalares

In [8]:
# Multiplicación por un escalar
scalar_mult = a * 10
print("Multiplicación por escalar:", scalar_mult)

# Exponenciación
exp_array = a ** 2
print("Exponenciación:", exp_array)


Multiplicación por escalar: [10 20 30]
Exponenciación: [1 4 9]


**Ejercicios**

Dado x = np.array([2, 4, 6]) y y = np.array([1, 3, 5]), calcula x * y y x / y.


In [12]:
x = np.array([2, 4, 6])
y = np.array([1, 3, 5])
print("x * y:", x * y)
print("x / y:", x / y)

x * y: [ 2 12 30]
x / y: [2.         1.33333333 1.2       ]


Eleva al cubo cada elemento del array x.


In [13]:
x**3

array([  8,  64, 216])

Suma 5 a cada elemento del array y y luego calcula la raíz cuadrada.

In [15]:
(y + 5)**0.5

array([2.44948974, 2.82842712, 3.16227766])

### 4.2. Funciones Matemáticas

NumPy proporciona funciones universales (ufuncs) para realizar operaciones matemáticas.

**Ejemplo 1:** Funciones Estadísticas

In [10]:
array = np.array([1, 5, 2, 8, 3])

print("Suma total:", array.sum())
print("Promedio:", array.mean())
print("Mediana:", np.median(array))
print("Desviación estándar:", array.std(ddof=1))


Suma total: 19
Promedio: 3.8
Mediana: 3.0
Desviación estándar: 2.7748873851023217


**Ejemplo 2:** Funciones Trigonométricas y Exponenciales

In [16]:
angles = np.array([0, np.pi/2, np.pi])

print("Seno:", np.sin(angles))
print("Coseno:", np.cos(angles))
print("Exponencial:", np.exp(array))


Seno: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Coseno: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Exponencial: [2.71828183e+00 1.48413159e+02 7.38905610e+00 2.98095799e+03
 2.00855369e+01]


**Ejercicios**

Calcula el valor máximo y mínimo de un array aleatorio de forma (10,).


In [22]:
x = np.random.randint(0,100,(10,))
print(x)
print("Máximo:", x.max())
print("Mínimo:", x.min())

[79 88 69 24 14 52 80 90 60 88]
Máximo: 90
Mínimo: 14


Dado un array de ángulos en grados, conviértelos a radianes y calcula su seno.


In [28]:
x = np.array([0, 30, 45, 60, 90])
print("Seno:", np.sin(np.deg2rad(x)))

Seno: [0.         0.5        0.70710678 0.8660254  1.        ]


Genera un array y normalízalo restando la media y dividiendo por la desviación estándar.

In [27]:
x = np.random.randint(0,100,(10,))
print(x)

x_normalized = (x - x.mean())/x.std()
print(x_normalized)


[99 87  5 87 86 34  3  2 52 51]
[ 1.33063479  1.00072534 -1.25365592  1.00072534  0.97323288 -0.45637474
 -1.30864083 -1.33613328  0.03848944  0.01099698]


## 5. Indexación y Slicing

La indexación y el slicing te permiten acceder y modificar partes específicas de un array.

**Ejemplo 1:** Acceso a Elementos Individuales

In [31]:
array = np.array([[10, 20, 30], [40, 50, 60]])

# Acceder al elemento en la fila 1, columna 2
element = array[1, 2]
print("Elemento en (1, 2):", element)


Elemento en (1, 2): 60


**Ejemplo 2:** Slicing de Subarrays

In [33]:
# Obtener la primera fila
first_row = array[0, :]
print("Primera fila:", first_row)

# Obtener la segunda columna
second_col = array[:, 1]
print("Segunda columna:", second_col)

# Obtener un subarray de forma (2, 2)
subarray = array[:, :2]
print("Subarray:\n", subarray)


Primera fila: [10 20 30]
Segunda columna: [20 50]
Subarray:
 [[10 20]
 [40 50]]


**Ejercicios**

Dado un array de forma (5, 5), extrae la submatriz central de forma (3, 3).


In [39]:
x = np.random.randint(0,100,(5,5))
print(x)
print(x[1:4,1:4])

[[23 15 12 14 89]
 [40 94 74 76 57]
 [94 91 80 14  1]
 [ 9 66 10  5 22]
 [63 36 60 47  1]]
[[94 74 76]
 [91 80 14]
 [66 10  5]]


Cambia los elementos de la última fila de un array a ceros.


In [40]:
x[-1, :] = 0
print(x)

[[23 15 12 14 89]
 [40 94 74 76 57]
 [94 91 80 14  1]
 [ 9 66 10  5 22]
 [ 0  0  0  0  0]]


Invierte el orden de los elementos en un array unidimensional.


In [48]:
np.random.seed(42)

x = np.random.rand(5)
print(f"Current: {x}")
x_inv = x[::-1]
print(f"Inverted: {x_inv}")

Current: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Inverted: [0.15601864 0.59865848 0.73199394 0.95071431 0.37454012]


## 6. Manipulación de la Forma

### 6.1. Reshape

Cambiar la forma de un array sin alterar sus datos.

**Ejemplo 1:** Reshape Básico

In [49]:
array = np.arange(12)
reshaped_array = array.reshape(3, 4)
print("Array reestructurado:\n", reshaped_array)


Array reestructurado:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Ejemplo 2:** Reshape con -1

In [50]:
# NumPy calcula automáticamente el tamaño faltante
reshaped_array = array.reshape(2, -1)
print("Array reestructurado con -1:\n", reshaped_array)


Array reestructurado con -1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


**Ejercicios**

Convierte un array de forma (6,) en uno de forma (2, 3).


In [51]:
x = np.arange(6)
print(x)
print(x.reshape(2,3))

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


Dado un array de forma (4, 3), conviértelo en uno de forma (2, 2, 3).


In [53]:
x = np.random.randint(0,100,(4,3))
print(x)
print("\n")
print(x.reshape(2,2,3))

[[29 37  1]
 [63 59 20]
 [32 75 57]
 [21 88 48]]


[[[29 37  1]
  [63 59 20]]

 [[32 75 57]
  [21 88 48]]]


Aplana un array multidimensional a un array unidimensional.

In [54]:
x.flatten()

array([29, 37,  1, 63, 59, 20, 32, 75, 57, 21, 88, 48])

### 6.2. Transposición

Intercambia los ejes de un array.

**Ejemplo 1:** Transposición de Matriz

In [55]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
transposed_matrix = matrix.T
print("Matriz original:\n", matrix)
print("Matriz transpuesta:\n", transposed_matrix)


Matriz original:
 [[1 2]
 [3 4]
 [5 6]]
Matriz transpuesta:
 [[1 3 5]
 [2 4 6]]


**Ejemplo 2:** Transposición de Arrays de Mayor Dimensión

In [57]:
array = np.arange(24).reshape(2, 3, 4)
print(array)
transposed_array = array.transpose(1, 0, 2)
print("Array transpuesto:\n", transposed_array.shape)
print(transposed_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Array transpuesto:
 (3, 2, 4)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


**Ejercicios**

Transpón una matriz de forma (5, 3).


In [58]:
x = np.random.randint(0,100,(5,3))
print(x)
print("\n")
print(x.T)

[[90 58 41]
 [91 59 79]
 [14 61 61]
 [46 61 50]
 [54 63  2]]


[[90 91 14 46 54]
 [58 59 61 61 63]
 [41 79 61 50  2]]


Dado un array de forma (2, 3, 4), reorganiza sus ejes para obtener un array de forma (4, 2, 3).


In [59]:
x = np.random.randint(0,100,(2,3,4))
print(x)
print("\n")
print(x.transpose(2,0,1))

[[[50  6 20 72]
  [38 17  3 88]
  [59 13  8 89]]

 [[52  1 83 91]
  [59 70 43  7]
  [46 34 77 80]]]


[[[50 38 59]
  [52 59 46]]

 [[ 6 17 13]
  [ 1 70 34]]

 [[20  3  8]
  [83 43 77]]

 [[72 88 89]
  [91  7 80]]]


Verifica que la transposición de una matriz simétrica es igual a la matriz original.

In [67]:
x = np.random.randint(0,100,(5,5))

x_T = x.T

x_symmetric = (x + x_T)/2

print(x_symmetric)
print("\n")
print(x_symmetric.T)

[[12.  29.  63.  70.5 86.5]
 [29.  65.  23.  36.5 61. ]
 [63.  23.  27.  44.  69.5]
 [70.5 36.5 44.  74.  45.5]
 [86.5 61.  69.5 45.5 26. ]]


[[12.  29.  63.  70.5 86.5]
 [29.  65.  23.  36.5 61. ]
 [63.  23.  27.  44.  69.5]
 [70.5 36.5 44.  74.  45.5]
 [86.5 61.  69.5 45.5 26. ]]


### 6.3. Concatenación y División de Arrays

Combina o divide arrays.

**Ejemplo 1:** Concatenación

In [71]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenación unidimensional
concat_array = np.concatenate((a, b))
print("Array concatenado:", concat_array)

# Concatenación bidimensional
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

concat_2d = np.concatenate((array1, array2), axis=0)
print("Array 2D concatenado:\n", concat_2d)


Array concatenado: [1 2 3 4 5 6]
Array 2D concatenado:
 [[1 2]
 [3 4]
 [5 6]]


**Ejemplo 2:** División


In [72]:
# División en arrays más pequeños
split_array = np.array_split(concat_array, 3)
print("Arrays divididos:", split_array)


Arrays divididos: [array([1, 2]), array([3, 4]), array([5, 6])]


**Ejercicios**

Une dos matrices de forma (2, 2) para crear una de forma (2, 4).


In [101]:
np.random.seed(42)

x = np.random.randint(0,100,(2,2))
y = np.random.randint(0,100,(2,2))

print(x)
print("\n")
print(y)
print("\n")

print(np.concatenate((x,y), axis=1))

[[51 92]
 [14 71]]


[[60 20]
 [82 86]]


[[51 92 60 20]
 [14 71 82 86]]


Divide un array de forma (12,) en tres arrays iguales.


In [102]:
x = np.arange(12)
print(x)
print("\n")
print(np.array_split(x,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


Combina verticalmente dos arrays de forma (3, 2).

In [103]:
x = np.random.randint(0,100,(3,2))
y = np.random.randint(0,100,(3,2))

print(x)
print("\n")
print(y)
print("\n")

print(np.concatenate((x,y), axis=0))


[[74 74]
 [87 99]
 [23  2]]


[[21 52]
 [ 1 87]
 [29 37]]


[[74 74]
 [87 99]
 [23  2]
 [21 52]
 [ 1 87]
 [29 37]]


In [114]:
# concatenation of 2 matrices of shape 2,2,4 on the thrid dimention
np.random.seed(42)

x = np.random.randint(0,100,(2,2,3))
y = np.random.randint(0,100,(2,2,3))

print(x)
print("\n")
print(y)
print("\n")

print(np.concatenate((x,y), axis=1, out=None))


[[[51 92 14]
  [71 60 20]]

 [[82 86 74]
  [74 87 99]]]


[[[23  2 21]
  [52  1 87]]

 [[29 37  1]
  [63 59 20]]]


[[[51 92 14]
  [71 60 20]
  [23  2 21]
  [52  1 87]]

 [[82 86 74]
  [74 87 99]
  [29 37  1]
  [63 59 20]]]


## 7. Broadcasting


Broadcasting en NumPy es una poderosa técnica que permite realizar operaciones entre arreglos de diferentes formas (shapes) de manera eficiente y sin necesidad de escribir bucles explícitos. Se utiliza para extender las dimensiones de un arreglo más pequeño para que sea compatible con el arreglo más grande en una operación.

**Ejemplo 1:** Suma con Broadcasting

In [73]:
a = np.array([1, 2, 3]) # Forma: (3,)
b = np.array([[10], [20], [30]]) # Forma: (3, 1)

result = a + b
print("Resultado de broadcasting:\n", result)

Resultado de broadcasting:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


**Ejemplo 2:** Multiplicación con Broadcasting

In [74]:
array = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

result = array * scalar
print("Multiplicación por escalar:\n", result)


Multiplicación por escalar:
 [[ 2  4  6]
 [ 8 10 12]]


In [78]:
a = np.array([1, 2])  # Forma: (2,)
b = np.array([[10],   # Forma: (3, 1)
              [20],
              [30]])

# Esto lanza un error
result = a + b
result
# El error ocurre porque las dimensiones (2,) y (3, 1) no son compatibles.

array([[11, 12],
       [21, 22],
       [31, 32]])

In [79]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # Forma: (2, 3)
b = np.array([10, 20, 30])            # Forma: (3,)

result = a + b
print(result)


[[11 22 33]
 [14 25 36]]


**Normalización de Datos:**

Supongamos que tienes un arreglo con datos y quieres normalizar cada columna restando el promedio y dividiendo entre la desviación estándar:

In [80]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

mean = data.mean(axis=0)  # Promedio de cada columna
std = data.std(axis=0)    # Desviación estándar de cada columna

normalized = (data - mean) / std
print(normalized)


[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


Si intentas operar arreglos con formas incompatibles, obtendrás un error como:



Ejercicios

Suma un vector de forma (3,) a una matriz de forma (3, 3).


Multiplica cada columna de una matriz de forma (4, 3) por un vector de forma (3,).


Resta un escalar de todos los elementos de un array.


## 8. Álgebra Lineal

NumPy proporciona funciones avanzadas para realizar operaciones de álgebra lineal.



### 8.1. Producto Punto y Producto Cruz



### **Producto Punto (o Escalar)**

El producto punto de dos vectores es una operación que resulta en un número escalar. Se calcula multiplicando las componentes correspondientes de los vectores y sumándolas.




Dado dos vectores:
$
\mathbf{A} = (a_1, \; a_2, \; a_3) \quad \text{y} \quad \mathbf{B} = (b_1, \; b_2, \; b_3)
$



Cálculo del producto punto



$
\mathbf{A} \cdot \mathbf{B} = a_1 b_1 + a_2 b_2 + a_3 b_3
$

**Ejemplo 1:** Producto Punto


In [81]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([3, 4, 5])

dot_product = np.dot(vector1, vector2)
print("Producto punto:", dot_product)


Producto punto: 26


### **Producto Cruz (o Vectorial)**

El producto cruz de dos vectores da como resultado un nuevo vector perpendicular a ambos vectores originales.




Dado dos vectores:
$
\mathbf{A} = (a_1, \; a_2, \; a_3) \quad \text{y} \quad \mathbf{B} = (b_1, \; b_2, \; b_3)
$



Cálculo del producto cruz Usando componentes:

$
\mathbf{A} \times \mathbf{B} = \left( a_2 b_3 - a_3 b_2, \; a_3 b_1 - a_1 b_3, \; a_1 b_2 - a_2 b_1 \right)
$

O utilizando el determinante de una matriz:


$
\mathbf{A} \times \mathbf{B} = \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3 \\
\end{vmatrix}
$

Desarrollando el determinante:

$
\mathbf{A} \times \mathbf{B} = \left( a_2 b_3 - a_3 b_2 \right) \mathbf{i} - \left( a_1 b_3 - a_3 b_1 \right) \mathbf{j} + \left( a_1 b_2 - a_2 b_1 \right) \mathbf{k}
$

**Ejemplo 2:** Producto Cruz

In [85]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([3, 4, 5])

cross_product = np.cross(vector1, vector2)
print("Producto cruz:", cross_product)

Producto cruz: [-2  4 -2]


**Ejercicios**

Calcula el producto punto de dos vectores de tamaño 3.


Encuentra el producto cruz de los vectores [2, 3, 4] y [5, 6, 7].


Verifica que el producto punto de dos vectores perpendiculares es cero.

### 8.2. Operaciones con Matrices



**Operación Matmul (Multiplicación de Matrices)**

La operación matmul, abreviatura de matrix multiplication (multiplicación de matrices), es una operación fundamental en álgebra lineal que combina dos matrices para producir una tercera matriz. Esta operación es esencial en campos como matemáticas, física, ingeniería y ciencias de la computación.



<img src="https://www.includehelp.com/python/images/numpy-1.jpg" alt="HTML5 Icon" width="700" height="200" >



**Ejemplo 1:**  Multiplicación de Matrices

In [96]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 0], [1, 2]])

product = np.matmul(matrix1, matrix2)
print("Producto de matrices:\n", product)


Producto de matrices:
 [[ 4  4]
 [10  8]]


array([[2, 0, 4, 0],
       [1, 2, 2, 4],
       [6, 0, 8, 0],
       [3, 6, 4, 8]])

**Inversa**

La inversa de una matriz es un concepto fundamental en álgebra lineal. Dada una matriz cuadrada A, su inversa, denotada como
A**(−1), es otra matriz que cumple con la siguiente propiedad:

$
\mathbf{A} \times \mathbf{A}^{-1} = \mathbf{A}^{-1} \times \mathbf{A} = \mathbf{I}
$


In [87]:
matrix = np.array([[4, 7], [2, 6]])

# Inversa
inverse = np.linalg.inv(matrix)
print("Inversa de la matriz:\n", inverse)



Inversa de la matriz:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


**Determinante**

El determinante es una función que asigna a cada matriz cuadrada un número escalar. Es una herramienta fundamental en álgebra lineal, utilizada para determinar si una matriz es invertible, calcular áreas, volúmenes y resolver sistemas de ecuaciones lineales.

Considera la matriz:

$
\boldsymbol{A} = \begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
\end{pmatrix}
$

El determinante se calcula mediante la regla de Sarrus o por expansión de cofactores.

**Regla de Sarrus:**



 <img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/Regla_de_Sarrus_01.svg" alt="HTML5 Icon" width="300" height="300" >


$
\det(\boldsymbol{A}) = a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32} - (a_{13}a_{22}a_{31} + a_{11}a_{23}a_{32} + a_{12}a_{21}a_{33})
$

In [88]:
# Determinante
determinante = np.linalg.det(matrix)
print("Determinante de la matriz:", determinante)


Determinante de la matriz: 10.000000000000002


**Ejercicios**

Calcula el determinante de una matriz de 3x3.


Encuentra la matriz inversa de una matriz cuadrada.


Verifica que el producto de una matriz y su inversa es la matriz identidad.

**Ejercicio 1:** Multiplicación de Matrices y Producto Punto

- Crea dos matrices A y B de dimensiones compatibles.
- Calcula la multiplicación de matrices C=A×B.
- Calcula el producto punto de dos vectores.
- Verifica si la multiplicación de matrices es conmutativa en este caso (es decir, si A×B=B×A).

**Ejercicio 2:** Cálculo de la Inversa y Verificación

- Crea una matriz cuadrada invertible A.
- Calcula la inversa de A.
- Verifica que A×A**(−1) es la matriz identidad.

**Ejercicio 3:** Cálculo de Determinante, Valores y Vectores Propios

- Crea una matriz cuadrada A.
- Calcula el determinante de A.
- Calcula los valores propios y vectores propios de A.
- Verifica la relación A×v=λv para un par valor propio y vector propio.

### 8.3. Sistemas de Ecuaciones Lineales

Resuelve sistemas de ecuaciones lineales utilizando NumPy.




**Ejemplo 1:** Sistema de Ecuaciones

Resuelve el siguiente sistema:

2x + 3y =  8

 x − 4y = −2


In [89]:
# Coeficientes de las variables
A = np.array([[2, 3], [1, -4]])

# Vector de constantes
B = np.array([8, -2])

# Solución
solution = np.linalg.solve(A, B)
print("Solución del sistema:", solution)


Solución del sistema: [2.36363636 1.09090909]


**Ejemplo 2:** Sistema de Ecuaciones de Mayor Dimensión

Resuelve el sistema:
  
 x +  y +  z =  6

2x + 5y +  z = −4

2x + 3y + 8z = 27

In [90]:
A = np.array([[1, 1, 1], [2, 5, 1], [2, 3, 8]])
B = np.array([6, -4, 27])

solution = np.linalg.solve(A, B)
print("Solución del sistema:", solution)


Solución del sistema: [ 7.05263158 -4.26315789  3.21052632]


**Ejercicios**

Resuelve un sistema de ecuaciones de 3 variables y 3 ecuaciones.

$
\begin{aligned}
2x + 3y - z &= 5 \\
4x + y + 2z &= 6 \\
-3x + 2y + 3z &= -4
\end{aligned}
$

Verifica la solución del sistema sustituyendo los valores encontrados en las ecuaciones originales.


Intenta resolver un sistema de ecuaciones linealmente dependiente y observa el resultado.

$
\begin{aligned}
x + y &= 2 \\
2x + 2y &= 4
\end{aligned}
$

## 9. Ejercicios Prácticos

**Ejercicio 1: Estadísticas**

- Genera un array aleatorio de forma (4, 5) con números enteros entre 0 y 100.
- Calcula el promedio, el valor mínimo y su índice global.
- Encuentra el valor máximo de cada fila y de cada columna.

**Ejercicio 2: Manipulación de Forma**

- Crea una matriz de 3x3 con números consecutivos del 1 al 9.
- Transpón la matriz y aplana el resultado.
- Reshapea el array a una forma de (9, 1).

**Ejercicio 3: Álgebra Lineal**

Resuelve el sistema de ecuaciones:

3x +  2y −  z =  1

2x −  2y + 4z = −2

−x + 21y −  z =  0​


- Encuentra la solución para las variables x, y, z.
- Comprueba la solución sustituyéndola en las ecuaciones originales.
- Calcula el determinante de la matriz de coeficientes.


---

# Gracias por completar este laboratorio!

---